-- Write a query to list the first_name, last_name, and email of all customers living in the state of 'NY'.
select * from dbo.stores
select first_name, last_name, email, state from dbo.customers
where state = 'NY'

-- Retrieve all products from the products table that have a list_price greater than 500 and were released in the model_year 2019
select product_name, model_year, list_price 
from dbo.products
where model_year = 2019 and list_price > 500

-- List all store names and their full addresses (street, city, state, zip_code).
select store_name, street, city, state, zip_code
from dbo.stores

-- Display the order_id, order_date, and the full name (first_name + last_name) of the customer who placed each order.
select order_id, order_date, first_name, last_name 
from orders
left join dbo.customers
on orders.customer_id = customers.customer_id


-- List the names of all products alongside their corresponding category_name.
select product_name, category_name
from products
left join categories
on products.category_id = categories.category_id

-- For every item in the stocks table, show the store_name, product_name, and the quantity currently in stock.
select store_name, product_name, quantity 
from stocks
left join products
on stocks.product_id = products.product_id
left join stores
on stocks.store_id = stores.store_id

-- Show all orders handled by the staff member 'Mireya Copeland'. Include order_id, order_status, and order_date.
select order_id, order_status, order_date, first_name, last_name
from orders
left join staffs
on orders.staff_id = staffs.staff_id
where first_name = 'Mireya' and last_name = 'Copeland'


-- Find the total number of orders placed by each customer. Display the customer_id and the order count.
select customers.customer_id, count(order_id) as total_orders
from customers
left join orders
on customers.customer_id = orders.customer_id
group by customers.customer_id

-- Calculate the total revenue generated by each store_name. .
select store_name, sum(quantity*list_price) as Revenue
from order_items
left join orders on order_items.order_id = orders.order_id
left join stores on orders.store_id = stores.store_id
group by store_name
order by Revenue desc

-- Which product brand has the highest average list_price? Display the brand_name and the average price.
select brand_name, avg(products.list_price) as AverageListPrice from brands
left join products on products.brand_id = brands.brand_id
left join order_items on order_items.product_id = products.product_id
group by brand_name
order by AverageListPrice desc

-- Count how many different products are available in each category.
select category_name, count(product_id) as TotalProducts from categories
left join products on categories.category_id = products.category_id
group by category_name
order by TotalProducts desc

-- List all customers who have placed more than 3 orders.
select first_name, count(customers.customer_id) as TotalOrders from customers
left join orders on orders.customer_id = customers.customer_id
group by first_name
having count(customers.customer_id) > 3
order by TotalOrders desc


-- Retrieve the names of products that have never been ordered
select product_name from products
left join order_items
on products.product_id = order_items.product_id


-- For each store, find the staff member who has processed the highest number of orders.
with NumORders as
(select store_name, first_name, last_name, count(orders.staff_id) as TotalOrders,
rank() over(partition by store_name order by count(orders.staff_id) desc) as ranking from staffs
left join orders on orders.staff_id = staffs.staff_id
left join stores on stores.store_id = staffs.staff_id
group by store_name, first_name, last_name)

select store_name, first_name, TotalOrders from NumORders
where ranking = 1

-- Calculate the total discount amount given for each order, but only for orders that were shipped later than their required_date.
select * from orders, order_items
select orders.order_id, required_date, shipped_date, sum(quantity*list_price*discount) as Discount from orders
left join order_items on orders.order_id = order_items.order_id
where shipped_date > required_date
group by orders.order_id, required_date, shipped_date


-- Write a query to generate a report showing the category_name, total quantity sold, and total sales amount (after applying the discount) for the year 2017, grouped by category and sorted by total sales in descending order.
select 
category_name, 
sum(quantity) as TotalQuantity,
sum((order_items.list_price*quantity) - (discount*quantity)) as TotalDiscountedSales
from order_items
join products on products.product_id =order_items.product_id
join categories on categories.category_id = products.category_id
join orders on orders.order_id = order_items.order_id
where shipped_date between '2017-01-01' and '2017-12-31'
group by category_name
order by TotalDiscountedSales desc


select * from orders